version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - .:/data

  app:
    build: .
    volumes:
      - .:/Playground
    ports:
      - "3000:3000"
    depends_on:
      - redis

volumes:
  redis: